<template>
  <div
    :class="['icon-cell', { 'is-checked': isChecked }]"
    @click="onCheck">
    <span class="icon-cell__marked">
      <svg-icon
        name="selected"
        :size="24" />
    </span>
    <div class="icon-cell__svg">
      <svg-icon
        :name="name"
        :size="32" />
    </div>
    <p class="icon-cell__name">
      {{ name }}
    </p>
    <div class="icon-cell__toolbar">
      <div
        class="icon-cell__button"
        @click.stop="onCopy">
        <svg-icon
          name="copy"
          :size="14" />
        复制
      </div>
      <div
        class="icon-cell__button"
        @click.stop="onDownload">
        <svg-icon
          name="download"
          :size="14" />
        下载
      </div>
    </div>
  </div>
</template>

<script>
/**
 * IconCell.vue - Icon 示例栏组件
 * =============================================================
 * Created By: Yaohaixiao
 * Update: 2022.11.08
 */
import SvgIcon from '@/SvgIcon'

import { copyToClipboard, createAndDownloadFile } from '$utils/utils'
import { getStorage } from '$utils/storage'

export default {
  name: 'IconCell',
  componentName: 'IconCell',
  components: {
    SvgIcon
  },
  props: {
    symbol: {
      type: String,
      default: ''
    }
  },
  data() {
    return {
      name: '',
      isChecked: false
    }
  },
  watch: {
    symbol() {
      this.update()
    }
  },
  mounted() {
    this.update()

    this.$subscribe('clean:cart', this.update)
  },
  methods: {
    update() {
      const icons = getStorage('svg.icon.set')
      const keys = this.symbol.match(/icon-(\w+(-\w+)*)+/)

      this.name = keys[1]

      if (icons) {
        this.isChecked = JSON.parse(icons).indexOf(this.symbol) > -1
      } else {
        this.isChecked = false
      }
    },
    add(icon) {
      this.$broadcast('add:icon', icon)
    },
    remove(icon) {
      this.$broadcast('remove:icon', icon)
    },
    check(name, action = '加入') {
      this.$message.success({
        round: true,
        message: `图标“${name}”已${action}图标集购物车！`
      })
    },
    copy(name) {
      copyToClipboard(name)
      this.$message.success({
        round: true,
        message: `图标名“${name}”已复制到粘贴板！`
      })
    },
    download() {
      const pattern = /<symbol(([\s\S])*?)>(.*?)<\/symbol>/
      const symbol = this.symbol
      const paths = symbol.match(pattern)[3]
      const size = symbol.match(/viewBox="0 0 (.*?)"/)[1].split(' ')
      const width = size[0]
      const height = size[1]
      const svg =
        '<!-- Generated by svg-icon.vue -->\n' +
        '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="' +
        width +
        '" height="' +
        height +
        '" viewBox="0 0 ' +
        width +
        ' ' +
        height +
        '">\n' +
        '<title>' +
        this.name +
        '</title>\n' +
        paths +
        '\n' +
        '</svg>'

      createAndDownloadFile(`${this.name}.svg`, svg)
    },
    toggle() {
      this.isChecked = !this.isChecked
    },
    onCheck() {
      let action = ''
      const icon = this.symbol

      this.toggle()

      if (this.isChecked) {
        this.add(icon)
        action = '加入'
      } else {
        action = '移除'
        this.remove(icon)
      }

      this.check(this.name, action)
    },
    onCopy() {
      this.copy(this.name)
    },
    onDownload() {
      this.download()
    }
  }
}
</script>

<style lang="less">
@import './icon-cell';
</style>
