<template>
  <div
    :class="['icon-cell', { 'is-checked': checked }]"
    @click="onCheck">
    <span class="icon-cell__marked">
      <svg-icon
        name="selected"
        :size="24" />
    </span>
    <div class="icon-cell__svg">
      <svg-icon
        :name="name"
        :size="32" />
    </div>
    <p class="icon-cell__name">
      {{ name }}
    </p>
    <div class="icon-cell__toolbar">
      <div
        class="icon-cell__button"
        @click.stop="onCopy">
        <svg-icon
          name="copy"
          :size="14" />
        复制
      </div>
      <div
        class="icon-cell__button"
        @click.stop="onDownload">
        <svg-icon
          name="download"
          :size="14" />
        下载
      </div>
    </div>
  </div>
</template>

<script>
/**
 * IconCell.vue - Icon 示例栏组件
 * =============================================================
 * Created By: Yaohaixiao
 * Update: 2022.11.10
 */
import SvgIcon from '@/SvgIcon'

import { copyToClipboard, createAndDownloadFile } from '$utils/utils'
import { getStorage } from '$utils/storage'

export default {
  name: 'IconCell',
  componentName: 'IconCell',
  components: {
    SvgIcon
  },
  props: {
    symbol: {
      type: String,
      default: ''
    }
  },
  data() {
    return {
      name: '',
      checked: false
    }
  },
  watch: {
    symbol() {
      this.update()
    }
  },
  mounted() {
    this.update()

    this.$subscribe('update:icons', this.updateChecked)
    this.$subscribe('clean:cart', this.updateChecked)
  },
  beforeDestroy() {
    this.$unsubscribe('update:icons', this.updateChecked)
    this.$unsubscribe('clean:cart', this.updateChecked)
  },
  methods: {
    update() {
      const keys = this.symbol.match(/icon-(\w+(-\w+)*)+/)

      this.name = keys[1]

      this.updateChecked()
    },
    updateChecked() {
      const icons = getStorage('svg.icon.set')

      if (icons) {
        this.checked = JSON.parse(icons).indexOf(this.symbol) > -1
      } else {
        this.checked = false
      }
    },
    add(symbol) {
      this.$broadcast('add:icon', symbol)
    },
    remove(symbol) {
      this.$broadcast('remove:icon', symbol)
    },
    check(name, action = '加入') {
      this.$message.success({
        round: true,
        message: `图标 ${name} 已${action}购物车！`
      })
    },
    copy(name) {
      copyToClipboard(name)
      this.$message.success({
        round: true,
        message: `图标名 ${name} 已复制到粘贴板！`
      })
    },
    download() {
      const pattern = /<symbol(([\s\S])*?)>(.*?)<\/symbol>/
      const symbol = this.symbol
      const paths = symbol.match(pattern)[3]
      const size = symbol.match(/viewBox="0 0 (.*?)"/)[1].split(' ')
      const originWidth = parseInt(size[0], 10)
      const originHeight = parseInt(size[1], 10)
      const width = originWidth > 200 ? 200 : originWidth
      const height = originHeight > 200 ? 200 : originHeight
      const svg =
        '<!-- Generated by svg-icon.vue -->\n' +
        '<svg xmlns="http://www.w3.org/2000/svg" width="' +
        width +
        '" height="' +
        height +
        '" viewBox="0 0 ' +
        originWidth +
        ' ' +
        originHeight +
        '">\n' +
        '<title>' +
        this.name +
        '</title>\n' +
        paths +
        '\n' +
        '</svg>'

      createAndDownloadFile(`${this.name}.svg`, svg)
    },
    toggle() {
      this.checked = !this.checked
    },
    onCheck() {
      let action = ''
      const symbol = this.symbol

      this.toggle()

      if (this.checked) {
        this.add(symbol)
        action = '加入'
      } else {
        action = '移除'
        this.remove(symbol)
      }

      this.check(this.name, action)
    },
    onCopy() {
      this.copy(this.name)
    },
    onDownload() {
      this.download()
    }
  }
}
</script>

<style lang="less">
@import './icon-cell';
</style>
