<template>
  <base-drawer
    ref="drawer"
    :title="title"
    header-border
    size="medium"
    :buttons="buttons"
    custom-class="card-drawer"
    @close="onClose">
    <template v-slot:tabs>
      <base-tab-nav
        v-model="active"
        stretch
        :tabs="tabs"
        class="cart-drawer__tabs" />
    </template>
    <template
      v-if="isIconView"
      v-slot:toolbar>
      <base-header
        role="toolbar"
        flex
        height="inner"
        padding="inner"
        :border="true"
        class="cart-drawer__toolbar">
        <template v-slot:start>
          <base-checkbox v-model="isAllChecked">全选</base-checkbox>
        </template>
      </base-header>
    </template>
    <div :class="['cart-drawer__main', { 'is-auto': isIconView }]">
      <ul
        v-if="isIconView"
        class="cart-drawer__list">
        <template v-if="items.length > 0">
          <cart-drawer-item
            v-for="(item, i) in collections"
            :key="`item-${i}`"
            :symbol="item.symbol"
            :is-checked="item.checked"
            :index="i"
            @check="onCheck"
            @delete="onDelete" />
        </template>
        <cart-drawer-item
          v-else
          is-empty>
          <base-empty />
        </cart-drawer-item>
      </ul>
      <textarea
        v-else
        readonly
        :value="code"
        class="cart-drawer__code" />
    </div>
  </base-drawer>
</template>

<script>
/**
 * CartDrawer.vue - CartDrawer 组件
 * =============================================================
 * Created By: Yaohaixiao
 * Update: 2022.11.10
 */
import BaseDrawer from '$components/BaseDrawer'
import BaseHeader from '$components/BaseHeader'
import BaseTabNav from '$components/BaseTabNav'
import BaseCheckbox from '$components/BaseCheckbox'
import BaseEmpty from '$components/BaseEmpty'

import CartDrawerItem from '$components/CartDrawerItem'

import { clearStorage } from '$utils/storage'
import { copyToClipboard, createAndDownloadFile } from '$utils/utils'

export default {
  name: 'CartDrawer',
  componentName: 'CartDrawer',
  components: {
    BaseDrawer,
    BaseHeader,
    BaseTabNav,
    BaseCheckbox,
    BaseEmpty,
    CartDrawerItem
  },
  props: {
    title: {
      type: String,
      default: '购物车'
    },
    items: {
      type: Array,
      default: () => []
    }
  },
  data() {
    return {
      active: 'icon',
      tabs: [
        {
          label: 'SVG 图标',
          value: 'icon'
        },
        {
          label: 'JS 源代码',
          value: 'code'
        }
      ],
      collections: [],
      buttons: []
    }
  },
  computed: {
    isAllChecked() {
      const collections = this.collections
      return collections.length > 0 && collections.every((item) => item.checked)
    },
    isIconView() {
      return this.active === 'icon'
    },
    disabled() {
      return this.items.length === 0
    },
    code() {
      const iconSet = {
        title: 'SvgIcon 图标集',
        code: 'SvgIconSet',
        symbols: this.items
      }
      const json = JSON.stringify(iconSet, null, 2)

      return `// Generated by svg-icon.vue\nconst SvgIconSet = ${json}\n\nexport default SvgIconSet\n`
    },
    svg() {
      return (
        '<!-- Generated by svg-icon.vue -->\n' +
        '<svg id="svg-icons" aria-hidden="true" style="position:absolute;width:0;height:0;overflow:hidden;">\n' +
        this.items.join('\n') +
        '\n</svg>'
      )
    }
  },
  watch: {
    items() {
      this.update()
    }
  },
  created() {
    this.update()
  },
  mounted() {
    this.$subscribe('show:drawer', this.show)
    this.$subscribe('hide:drawer', this.hide)
  },
  beforeDestroy() {
    this.$unsubscribe('show:drawer', this.show)
    this.$unsubscribe('hide:drawer', this.hide)
  },
  methods: {
    update() {
      this.collections = this.items.map((item) => {
        return {
          checked: true,
          symbol: item
        }
      })

      this.buttons = [
        {
          name: 'cancel',
          text: '取消',
          size: 'small'
        },
        {
          name: 'clean',
          text: '清空',
          icon: 'trash',
          disabled: this.disabled,
          action: () => {
            clearStorage('svg.icon.set')

            this.$message.success({
              round: true,
              message: `购物车已清空！`
            })

            this.$broadcast('clean:cart')
          }
        },
        {
          name: 'download',
          text: '下载',
          icon: 'download',
          disabled: this.disabled,
          action: () => {
            if (this.isIconView) {
              createAndDownloadFile('svg-icon-set.svg', this.svg)
            } else {
              createAndDownloadFile('svg-icon-set.js', this.code)
            }
          }
        },
        {
          name: 'confirm',
          text: '复制',
          icon: 'copy',
          size: 'small',
          type: 'primary',
          disabled: this.disabled,
          action: () => {
            copyToClipboard(this.isIconView ? this.svg : this.code)
            this.$message.success({
              round: true,
              message: `代码已复制！`
            })
          }
        }
      ]
    },
    show() {
      this.$refs.drawer.open()
    },
    hide() {
      this.$refs.drawer.close()
    },
    close() {
      setTimeout(() => {
        this.$broadcast('show:cart')
      }, 300)
    },
    onClose() {
      this.close()
    },
    onCheck({ id, checked }) {
      const collections = this.collections

      collections[id].checked = checked
      this.collections = collections
    },
    onDelete({ symbol, name }) {
      this.$broadcast('remove:icon', symbol)

      this.$message.success({
        round: true,
        message: `图标 ${name} 已移除购物车！`
      })
    }
  }
}
</script>

<style scoped lang="less">
@import './cart-drawer';
</style>
