<template>
  <base-drawer
    ref="drawer"
    :title="title"
    size="medium"
    :buttons="buttons"
    custom-class="card-drawer"
    @close="onClose">
    <textarea
      readonly
      :value="code"
      class="cart-drawer__code" />
  </base-drawer>
</template>

<script>
/**
 * CartDrawer.vue - CartDrawer 组件
 * =============================================================
 * Created By: Yaohaixiao
 * Update: 2022.11.09
 */
import BaseDrawer from 'components/BaseDrawer'

import { setStorage, clearStorage } from '$utils/storage'
import { copyToClipboard, createAndDownloadFile } from '$utils/utils'

export default {
  name: 'CartDrawer',
  componentName: 'CartDrawer',
  components: {
    BaseDrawer
  },
  props: {
    title: {
      type: String,
      default: '购物车'
    },
    items: {
      type: Array,
      default: () => []
    }
  },
  data() {
    return {
      buttons: []
    }
  },
  computed: {
    disabled() {
      return this.items.length === 0
    },
    code() {
      const iconSet = {
        title: 'SvgIcon 图标集',
        code: 'SvgIconSet',
        symbols: this.items
      }
      const json = JSON.stringify(iconSet, null, 2)

      return `// Generated by svg-icon.vue\nconst SvgIconSet = ${json}\n\nexport default SvgIconSet\n`
    }
  },
  watch: {
    items() {
      this.update()
      setStorage('svg.icon.set', JSON.stringify(this.items))
    }
  },
  created() {
    this.update()
  },
  mounted() {
    this.$subscribe('show:drawer', this.show)
    this.$subscribe('hide:drawer', this.hide)
  },
  beforeDestroy() {
    this.$unsubscribe('show:drawer', this.show)
    this.$unsubscribe('hide:drawer', this.hide)
  },
  methods: {
    update() {
      this.buttons = [
        {
          name: 'cancel',
          text: '取消',
          size: 'small'
        },
        {
          name: 'clean',
          text: '清空',
          icon: 'trash',
          disabled: this.disabled,
          action: () => {
            clearStorage('svg.icon.set')

            this.$message.success({
              round: true,
              message: `购物车已清空！`
            })

            this.$broadcast('clean:cart')
          }
        },
        {
          name: 'download',
          text: '下载',
          icon: 'download',
          disabled: this.disabled,
          action: () => {
            createAndDownloadFile('svg-icon-set.js', this.code)
          }
        },
        {
          name: 'confirm',
          text: '复制',
          icon: 'copy',
          size: 'small',
          type: 'primary',
          disabled: this.disabled,
          action: () => {
            copyToClipboard(this.code)
            this.$message.success({
              round: true,
              message: `代码已复制！`
            })
          }
        }
      ]
    },
    show() {
      this.$refs.drawer.open()
    },
    hide() {
      this.$refs.drawer.close()
    },
    close() {
      setTimeout(() => {
        this.$broadcast('show:cart')
      }, 300)
    },
    onClose() {
      this.close()
    }
  }
}
</script>

<style scoped lang="less">
@import './cart-drawer';
</style>
