<template>
  <base-container>
    <app-header />
    <base-main
      use-main-tag
      flex
      overflow="hidden">
      <app-aside />
      <base-main overflow="hidden">
        <router-view />
      </base-main>
    </base-main>
    <the-cart :icons="icons" />
    <base-drawer
      ref="iconSetDrawer"
      title="图标集"
      size="medium"
      :buttons="buttons"
      @close="onDrawerClose">
      <textarea
        readonly
        :value="code"
        class="icons-code" />
    </base-drawer>
  </base-container>
</template>

<script>
/**
 * AppLayout.vue - 主题框架页
 * =============================================================
 * Created By: Yaohaixiao
 * Update: 2022.10.08
 */
import BaseContainer from 'components/BaseContainer'
import BaseMain from 'components/BaseMain'
import BaseDrawer from 'components/BaseDrawer'

import AppHeader from './AppHeader'
import AppAside from './AppAside'

import TheCart from 'components/TheCart'

import { copyToClipboard, createAndDownloadFile } from '$utils/utils'
import { getStorage, setStorage, clearStorage } from '$utils/storage'

export default {
  name: 'AppLayout',
  componentName: 'AppLayout',
  components: {
    BaseContainer,
    BaseMain,
    BaseDrawer,
    AppHeader,
    AppAside,
    TheCart
  },
  data() {
    return {
      icons: [],
      buttons: []
    }
  },
  computed: {
    isDisabled() {
      return this.icons.length === 0
    },
    code() {
      const iconSet = {
        title: 'SvgIcon 图标集',
        code: 'SvgIconSet',
        symbols: this.icons
      }
      const json = JSON.stringify(iconSet, null, 2)

      return `// Generated by svg-icon.vue\nconst SvgIconSet = ${json}\n\nexport default SvgIconSet\n`
    }
  },
  watch: {
    icons() {
      this.initButtons()
      setStorage('svg.icon.set', JSON.stringify(this.icons))
    }
  },
  created() {
    this.update()
  },
  mounted() {
    this.$subscribe('add:icon', this.add)
    this.$subscribe('remove:icon', this.remove)

    this.$subscribe('show:drawer', this.show)
    this.$subscribe('hide:drawer', this.hide)
  },
  beforeDestroy() {
    this.$unsubscribe('add:icon', this.add)
    this.$unsubscribe('remove:icon', this.remove)

    this.$unsubscribe('show:drawer', this.show)
    this.$unsubscribe('hide:drawer', this.hide)

    clearStorage('svg.icon.set')
  },
  methods: {
    update() {
      const icons = getStorage('svg.icon.set')

      if (icons) {
        this.icons = JSON.parse(icons)
      }

      this.initButtons()
    },
    initButtons() {
      this.buttons = [
        {
          name: 'cancel',
          text: '取消',
          size: 'small'
        },
        {
          name: 'clean',
          text: '清空',
          icon: 'trash',
          disabled: this.isDisabled,
          action: () => {
            this.icons = []
            clearStorage('svg.icon.set')
            this.$message.success({
              round: true,
              message: `图标集购物车已清空！`
            })

            this.$broadcast('clean:cart')
          }
        },
        {
          name: 'download',
          text: '下载',
          icon: 'download',
          disabled: this.isDisabled,
          action: () => {
            createAndDownloadFile('svg-icon-set.js', this.code)
          }
        },
        {
          name: 'confirm',
          text: '复制',
          icon: 'copy',
          size: 'small',
          type: 'primary',
          disabled: this.isDisabled,
          action: () => {
            copyToClipboard(this.code)
            this.$message.success({
              round: true,
              message: `图标集代码已复制到粘贴板！`
            })
          }
        }
      ]
    },
    show() {
      this.$refs.iconSetDrawer.open()
    },
    hide() {
      this.$refs.iconSetDrawer.close()
    },
    add(icon) {
      this.icons.push(icon)
    },
    remove(icon) {
      const index = this.icons.indexOf(icon)

      if (index < 0) {
        return false
      }

      this.icons.splice(index, 1)
    },
    onDrawerClose() {
      setTimeout(() => {
        this.$broadcast('show:cart')
      }, 300)
    }
  }
}
</script>

<style scoped lang="less">
.icons-code {
  margin: 0;
  width: 100%;
  height: 98%;
  line-height: 150%;
  padding: 1em;
  box-sizing: border-box;
  border: 1px solid @primary_border_color;
  border-radius: 4px;
  color: @code_text_color;
  font-family: @font_code_family;
  outline: none;
  overflow: auto;

  &:focus {
    border-color: @primary_color;
  }
}
</style>
